version: '3.9'

services:

  relay:
    image: traefik:2.2.8

  mysql:
    image: harbor.sting.dev/beez/beez-mysql:latest

  influxdb:
    image: influxdb:2.0.6-alpine
    environment:
      INFLUXD_LOG_LEVEL: error
      INFLUXD_PPROF_DISABLED: 'true'

  portal:
    image: harbor.sting.dev/beez/beez-portal:latest
    environment:
      APP_ENV: production
      LOGSTASH_LEVEL: NOTICE

  telegraf:
    image: telegraf:1.18.1

  grafana:
    image: grafana/grafana:7.1.3

  ttn:
    image: harbor.sting.dev/beez/beez-ttn:latest
    environment:
      LOG_LEVEL: WARNING
      LOGSTASH_LEVEL: WARNING
      LOGSTASH_ENV: 'production'
